export const UNIT_KERJA_OPTIONS = [
  "Deputi Bidang Investigasi",
  "Perwakilan BPKP Aceh",
  "Perwakilan BPKP Provinsi Sumatera Utara",
  "Perwakilan BPKP Provinsi Sumatera Barat",
  "Perwakilan BPKP Provinsi Riau",
  "Perwakilan BPKP Provinsi Jambi",
  "Perwakilan BPKP Provinsi Sumatera Selatan",
  "Perwakilan BPKP Provinsi Bengkulu",
  "Perwakilan BPKP Provinsi Lampung",
  "Perwakilan BPKP Provinsi DKI Jakarta",
  "Perwakilan BPKP Provinsi Banten",
  "Perwakilan BPKP Provinsi Jawa Barat",
  "Perwakilan BPKP Provinsi Jawa Tengah",
  "Perwakilan BPKP Provinsi D.I. Yogyakarta",
  "Perwakilan BPKP Provinsi Jawa Timur",
  "Perwakilan BPKP Provinsi Bali",
  "Perwakilan BPKP Provinsi Nusa Tenggara Barat",
  "Perwakilan BPKP Provinsi Nusa Tenggara Timur",
  "Perwakilan BPKP Provinsi Kalimantan Utara",
  "Perwakilan BPKP Provinsi Kalimantan Timur",
  "Perwakilan BPKP Provinsi Kalimantan Tengah",
  "Perwakilan BPKP Provinsi Kalimantan Barat",
  "Perwakilan BPKP Provinsi Kalimantan Selatan",
  "Perwakilan BPKP Provinsi Sulawesi Utara",
  "Perwakilan BPKP Provinsi Sulawesi Tengah",
  "Perwakilan BPKP Provinsi Sulawesi Barat",
  "Perwakilan BPKP Provinsi Sulawesi Tenggara",
  "Perwakilan BPKP Provinsi Sulawesi Selatan",
  "Perwakilan BPKP Provinsi Gorontalo",
  "Perwakilan BPKP Provinsi Maluku Utara",
  "Perwakilan BPKP Provinsi Maluku",
  "Perwakilan BPKP Provinsi Kepulauan Bangka Belitung",
  "Perwakilan BPKP Provinsi Kepulauan Riau",
  "Perwakilan BPKP Provinsi Papua",
  "Perwakilan BPKP Provinsi Papua Barat",
  "Perwakilan BPKP Provinsi Papua Barat Daya",
  "Perwakilan BPKP Provinsi Papua Tengah",
] as const;
